<?xml version="1.0"?>
<package format="3">
  <name>kingfisher_description</name>
  <version>1.0.0</version>
  <description>
    URDF/xacro description of the Clearpath Kingfisher M200 USV with Gazebo
    (gz-sim) plugins for use in the VRX simulation environment.
  </description>
  <maintainer email="luisfelipewb@gmail.com">Luis Batista</maintainer>
  <author email="mpurvis@clearpathrobotics.com">Mike Purvis</author>
  <license>BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>xacro</depend>
  <exec_depend>wamv_gazebo</exec_depend>
  <exec_depend>vrx_gazebo</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
